# Generated by Django 4.0.6 on 2022-07-20 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('user_data_birthday', models.DateField(blank=True, null=True)),
                ('user_location', models.CharField(blank=True, max_length=100, null=True)),
                ('user_country', models.CharField(blank=True, max_length=50, null=True)),
                ('user_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('user_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('user_education', models.CharField(blank=True, max_length=200, null=True)),
                ('year_ending', models.DateField(blank=True, null=True)),
                ('education', models.CharField(max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
